steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/assignment1-2-418206/my-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/assignment1-2-418206/my-image']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/assignment1-2-418206/my-image', '.']
  dir: 'backend' 
  entrypoint: '/bin/bash'
  env:
    - 'PIP_CACHE_DIR=/workspace/.cache/pip'
  args:
    - '-c'
    - |
      pip install -r requirements.txt
      # Additional commands can be added here if needed
artifacts:
  objects:
    location: 'gs://assign1-2-cloudbuild-logs/'
